---
title: "R Notebook"
output: html_notebook
---
Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(tidyverse)
library(RMySQL)
library(DBI)
library(tidytext)
library(wordcloud)
```


```{r}
# Connect to a SQLite in-memory database
database <- dbConnect(MySQL(), 
                      dbname = "wdl_database",
                      host = "localhost",
                      user = "user",
                      password = "password",
                      port = 3306)

dfData <- dbGetQuery(database, "SELECT * FROM discord_messages")
```


```{sql connection=database}
    SELECT
    UserId,
    Name,
    COUNT(MessageId) AS TotalMessages,
    DATE_FORMAT(Timestamp, '%Y-%m') AS Month
FROM
    wdl_database.discord_messages
WHERE
    Name IN ('theycallmeq', 'jbuwu', 'snozledozle', 'thefyreprophecy', 'joppertje','lykozen','coeus._','coeus7680')
GROUP BY
    UserId, Name, DATE_FORMAT(Timestamp, '%Y-%m')
ORDER BY
    DATE_FORMAT(Timestamp, '%Y-%m');
```


```{r}
result_messagespermonth<- dbGetQuery(database, "
    SELECT
    UserId,
    Name,
    COUNT(MessageId) AS TotalMessages,
    DATE_FORMAT(Timestamp, '%Y-%m') AS Month
FROM
    wdl_database.discord_messages
WHERE
    Name IN ('theycallmeq', 'jbuwu', 'snozledozle', 'thefyreprophecy', 'joppertje','lykozen','coeus._','coeus7680')
GROUP BY
    UserId, Name, DATE_FORMAT(Timestamp, '%Y-%m')
ORDER BY
    DATE_FORMAT(Timestamp, '%Y-%m');
")
```
```{r}
plot_messagepermonth <- ggplot(result_messagespermonth, aes(x = Month, y = TotalMessages, fill = Name)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +  # Rotate x-axis labels if needed
  labs(title = "Monthly Messages per User", 
       x = "Month", 
       y = "Total Messages")

ggplotly(plot_messagepermonth)
```

```{sql connection=database}
SELECT COUNT(*) as TotalMessages
FROM wdl_database.discord_messages;
```
```{r}
result_totalmessages<- dbGetQuery(database, "
SELECT COUNT(*) as TotalMessages
FROM wdl_database.discord_messages;
")
```

```{sql connection=database}
SELECT
    CASE 
        WHEN Name = 'coeus._' OR Name = 'coeus7680' THEN 'coeus'
        ELSE Name
    END AS NameAlias,
    COUNT(DISTINCT Id) as MostMessages
FROM
    wdl_database.discord_messages
WHERE
    Name IN ('theycallmeq', 'jbuwu', 'snozledozle', 'thefyreprophecy', 'joppertje', 'lykozen', 'coeus._', 'coeus7680')
GROUP BY
    NameAlias
ORDER BY
    MostMessages ASC
LIMIT 1;
```
```{r}
result_mostmessages<- dbGetQuery(database, "
SELECT Name, COUNT(distinct Id) as MostMessages 
FROM wdl_database.discord_messages
GROUP BY Name
ORDER BY MostMessages DESC
LIMIT 1;
")

result_leastmessages<- dbGetQuery(database, "
SELECT
    CASE 
        WHEN Name = 'coeus._' OR Name = 'coeus7680' THEN 'coeus'
        ELSE Name
    END AS NameAlias,
    COUNT(DISTINCT Id) as MostMessages
FROM
    wdl_database.discord_messages
WHERE
    Name IN ('theycallmeq', 'jbuwu', 'snozledozle', 'thefyreprophecy', 'joppertje', 'lykozen', 'coeus._', 'coeus7680')
GROUP BY
    NameAlias
ORDER BY
    MostMessages ASC
LIMIT 1;
")
```




```{sql connection=database}
SELECT *
FROM wdl_database.discord_messages
WHERE Content LIKE '%http%';
```


```{sql connection=database}
SELECT PremiumType, 
       GROUP_CONCAT(DISTINCT Name ORDER BY Name SEPARATOR ', ') AS Users, 
       COUNT(DISTINCT Name) AS UniqueUserCount
FROM wdl_database.discord_messages
WHERE PremiumType <> 'none'
GROUP BY PremiumType;
```

```{r}
result_nitrodistrobutionperusers<- dbGetQuery(database, "
SELECT PremiumType, 
       GROUP_CONCAT(DISTINCT Name ORDER BY Name SEPARATOR ', ') AS Users, 
       COUNT(DISTINCT Name) AS UniqueUserCount
FROM wdl_database.discord_messages
WHERE PremiumType <> 'none'
GROUP BY PremiumType;
")
```

```{r}
plot_ly(result_nitrodistrobutionperusers, labels = ~PremiumType, values = ~UniqueUserCount, type = 'pie',
  textinfo = 'label+percent', insidetextorientation = 'radial') %>%
  layout(title = 'Distribution of Premium Types Among Users')

```


```{sql connection=database}
    SELECT
    Name,
    COUNT(MessageId) AS TotalMessages
FROM
    wdl_database.discord_messages
WHERE
    Name IN ('theycallmeq', 'jbuwu', 'snozledozle', 'thefyreprophecy', 'joppertje','lykozen','coeus._','coeus7680')
GROUP BY
    Name
HAVING
    COUNT(MessageId) >= 100;
```
```{r}
result_totalmessagesperuser<- dbGetQuery(database, "
    SELECT
    Name,
    COUNT(MessageId) AS TotalMessages
FROM
    wdl_database.discord_messages
WHERE
    Name IN ('theycallmeq', 'jbuwu', 'snozledozle', 'thefyreprophecy', 'joppertje','lykozen','coeus._','coeus7680')
GROUP BY
    Name
HAVING
    COUNT(MessageId) >= 100;
")
```

```{r}
plot_totalmessagesperuser <- ggplot(result_totalmessagesperuser, aes(x = Name, y = TotalMessages, fill = Name)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Total Messages per User",
       x = "User Name",
       y = "Total Messages") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for readability

# Convert to an interactive plotly object
ggplotly(plot_totalmessagesperuser)
```

```{r}
word_frequencies <- dfData %>% 
  unnest_tokens(word, Content) %>%  # Split text into words
  count(word, sort = TRUE)          # Count and sort by frequency
top_words <- head(word_frequencies, 50)
print(top_words)
```
```{r}
# Assuming top_words is already created and contains the top 50 words
plot_topwords <- ggplot(top_words, aes(x = reorder(word, n), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flips the coordinates to make the plot horizontal
  labs(title = "Top 50 Word Frequencies",
       x = "Words",
       y = "Frequency") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))  # Adjust x-axis labels for readability

ggplotly(plot_topwords)
```



```{sql connection=database}
SELECT UserId, Name, COUNT(*) as TimesSaid
FROM wdl_database.discord_messages
WHERE Content LIKE '%thing%'
GROUP BY UserId, Name
ORDER BY TimesSaid DESC;
```

